MODULE = openwsn_stack

INCLUDES += -I./
INCLUDES += -I../openwsn/02a-MAClow
INCLUDES += -I../openwsn/02b-MAChigh
INCLUDES += -I../openwsn/03a-IPHC
INCLUDES += -I../openwsn/03b-IPv6
INCLUDES += -I../openwsn/04-TRAN
INCLUDES += -I../openwsn/cross-layers
INCLUDES += -I../openwsn/07-App/tcpinject
INCLUDES += -I../openwsn/07-App/udpinject


include $(RIOTBASE)/Makefile.base
