MODULE = openwsn_stack

INCLUDES += -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/cpu/arm_common/include -I$(RIOTBASE)/sys/net/include/
INCLUDES += -I$(CURDIR)/02a-MAClow
INCLUDES += -I$(CURDIR)/02b-MAChigh
INCLUDES += -I$(CURDIR)/03a-IPHC
INCLUDES += -I$(CURDIR)/03b-IPv6
INCLUDES += -I$(CURDIR)/04-TRAN
INCLUDES += -I$(CURDIR)/07-App/ohlone
INCLUDES += -I$(CURDIR)/07-App/tcpecho
INCLUDES += -I$(CURDIR)/07-App/tcpinject
INCLUDES += -I$(CURDIR)/07-App/tcpprint
INCLUDES += -I$(CURDIR)/cross-layers

# DIRS += rinfo
# DIRS += r6t
# DIRS += rwellknown
# DIRS += ohlone
# DIRS += tcpecho
# DIRS += tcpinject
# DIRS += tcpprint
# DIRS += udpecho
# DIRS += udpinject
# DIRS += udplatency
# DIRS += udpprint
# DIRS += udprand
# DIRS += udpstorm

include $(RIOTBASE)/Makefile.base
