MODULE = openwsn_stack

INCLUDES += -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/cpu/arm_common/include -I$(RIOTBASE)/sys/net/include/
INCLUDES += -I../../drivers
INCLUDES += -I../02a-MAClow
INCLUDES += -I../02b-MAChigh
INCLUDES += -I../03a-IPHC
INCLUDES += -I../03b-IPv6
INCLUDES += -I../04-TRAN
INCLUDES += -I../07-App/ohlone
INCLUDES += -I../07-App/tcpecho
INCLUDES += -I../07-App/tcpinject
INCLUDES += -I../07-App/tcpprint
INCLUDES += -I../07-App/udpecho
INCLUDES += -I../07-App/udpinject
INCLUDES += -I../07-App/udplatency
INCLUDES += -I../07-App/udpprint
INCLUDES += -I../07-App/udprand
INCLUDES += -I../07-App/udpstorm
INCLUDES += -I../cross-layers

include $(RIOTBASE)/Makefile.base
