MODULE =$(BOARD)_base

INCLUDES += -I$(RIOTBASE)/drivers/at86rf231/include
INCLUDES += -I$(RIOTBASE)/sys/net/include
INCLUDES += -I$(RIOTBASE)/sys/include

include $(RIOTBOARD)/$(BOARD)/Makefile.include

include $(RIOTBASE)/Makefile.base
