MODULE = openwsn_stack

INCLUDES += -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/cpu/arm_common/include -I$(RIOTBASE)/cpu/msp430-common/include -I$(RIOTBASE)/sys/net/include/

INCLUDES += -Ibsp -Ibsp/riot -Ikernel -Idrivers
INCLUDES += -Iopenwsn/02a-MAClow
INCLUDES += -Iopenwsn/02b-MAChigh
INCLUDES += -Iopenwsn/03a-IPHC
INCLUDES += -Iopenwsn/03b-IPv6
INCLUDES += -Iopenwsn/04-TRAN
INCLUDES += -Iopenwsn/cross-layers
INCLUDES += -Iopenwsn/07-App/rinfo
INCLUDES += -Iopenwsn/07-App/rwellknown
INCLUDES += -Iopenwsn/07-App/r6t
INCLUDES += -Iopenwsn/07-App/rleds
INCLUDES += -Iopenwsn/07-App/ohlone
INCLUDES += -Iopenwsn/07-App/tcpecho
INCLUDES += -Iopenwsn/07-App/tcpinject
INCLUDES += -Iopenwsn/07-App/tcpprint
INCLUDES += -Iopenwsn/07-App/udpecho
INCLUDES += -Iopenwsn/07-App/udpinject
INCLUDES += -Iopenwsn/07-App/udplatency
INCLUDES += -Iopenwsn/07-App/udpprint
INCLUDES += -Iopenwsn/07-App/udprand
INCLUDES += -Iopenwsn/07-App/udpstorm

DIRS =
DIRS += bsp/riot
DIRS += drivers
DIRS += kernel
DIRS += openwsn/02a-MAClow
DIRS += openwsn/02b-MAChigh
DIRS += openwsn/03a-IPHC
DIRS += openwsn/03b-IPv6
DIRS += openwsn/04-TRAN
DIRS += openwsn/cross-layers
DIRS += openwsn/07-App/rinfo
DIRS += openwsn/07-App/rwellknown
DIRS += openwsn/07-App/r6t
DIRS += openwsn/07-App/ohlone
DIRS += openwsn/07-App/tcpecho
DIRS += openwsn/07-App/tcpinject
DIRS += openwsn/07-App/tcpprint
DIRS += openwsn/07-App/udpecho
DIRS += openwsn/07-App/udpinject
DIRS += openwsn/07-App/udplatency
DIRS += openwsn/07-App/udpprint
DIRS += openwsn/07-App/udprand
DIRS += openwsn/07-App/udpstorm

include $(RIOTBASE)/Makefile.base
